

version: '3.8'


services:


  nginx:

    build:
      context:                  ./requirements/nginx
    container_name:             ${NGINX_CONTAINER_NAME}
    image:                      ${NGINX_IMAGE_NAME}
    env_file:
      - .env
    # depends_on:
      # - wordpress
      # - db

    ports:
      - "${NGINX_PORT}:443"
    networks:
      - ${NETWORK_NAME}
    volumes:
      # In case of our poject we dont need a separate nginx volume
      #   - ${NGINX_VOLUME}:/var/www/html
      - ${WP_VOLUME}:/var/www/html
    
    restart:                    on-failure


#   wordpress:
  
#     build:
#       context:                  ./requirements/wordpress
#     container_name:             ${WP_CONTAINER_NAME}
#     image:                      ${WP_IMAGE_NAME}
#     env_file:
#       - .env
#     # depends_on:
#     #   - db

#     networks:
#       - ${NETWORK_NAME}
#     volumes:
#       - ${WP_VOLUME}:/var/www/html

#     restart:                    on-failure

# volumes:
#   # ${NGINX_VOLUME}:
#   ${WP_VOLUME}:

networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}
    driver: bridge
