

version: '3.8'


services:


  nginx:

    container_name:             ${NGINX_CONTAINER_NAME}
    image:                      ${NGINX_IMAGE_NAME}
    build:
      context:                  ./requirements/nginx

    restart:                    on-failure

    env_file:
      - .env

    # volumes:
    #   # In case of our poject we dont need a separate nginx volume
    #   #   - ${NGINX_VOLUME}:/var/www/html
    #   - ${WP_VOLUME}:/var/www/html

    ports:
      - "${NGINX_PORT}:443"

    # depends_on:
      # - wordpress
      # - db

    networks:
      - ${NETWORK_NAME}


#   wordpress:
  
#     build:
#       context:                  ./requirements/wordpress
#     container_name:             ${WP_CONTAINER_NAME}
#     image:                      ${WP_IMAGE_NAME}
#     env_file:
#       - .env
#     # depends_on:
#     #   - db

#     networks:
#       - ${NETWORK_NAME}
#     volumes:
#       - ${WP_VOLUME}:/var/www/html

#     restart:                    on-failure

# volumes:
#   # ${NGINX_VOLUME}:
#   ${WP_VOLUME}:

networks:
  inception_net:
    name: ${NETWORK_NAME}
    driver: bridge
